# SPDX-License-Identifier: MIT

- type: entity
  name: boîte de menottes
  parent: BoxCardboard
  id: BoxHandcuff
  description: Une boîte pleine de menottes.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: Handcuffs
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: handcuff

- type: entity
  name: boîte de serflex
  parent: BoxCardboard
  id: BoxZiptie
  description: Une boîte pleine de serflex.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: Zipties
        amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: ziptie

- type: entity
  name: boîte de grenades aveuglantes
  parent: BoxCardboard
  id: BoxFlashbang
  description: 'WARNING: These devices are extremely dangerous and can cause blindness or deafness in repeated use.'
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: boîte de grenades stinger
  parent: BoxCardboard
  id: BoxStinger
  description: Une boîte pleine de grenades stinger. Dispersez-vous !
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: GrenadeStinger
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: boîte de grenades lacrymogènes
  parent: BoxCardboard
  id: BoxTearGas
  description: Une boîte pleine de grenades lacrymogènes. Retenez votre souffle.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: TearGasGrenade
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: boîte de visières de sécurité
  parent: BoxCardboard
  id: BoxSechud
  description: Une boîte de visières de sécurité.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ClothingEyesHudSecurity
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sechud

- type: entity
  name: boîte de lunettes de sécurité
  parent: BoxCardboard
  id: BoxSecglasses
  description: Une boîte de lunettes de sécurité.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ClothingEyesGlassesSecurity
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: secglasses

- type: entity
  name: boîte de lunettes de soleil
  parent: BoxCardboard
  id: BoxSunglasses
  description: Une boîte de lunettes de soleil résistantes aux flashs.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ClothingEyesGlassesSunglasses
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sunglasses

- type: entity
  name: boîte de tampons médico-légaux
  parent: BoxCardboard
  id: BoxForensicPad
  description: Une boîte de tampons médico-légaux.
  components:
  - type: Item
    shape:
    - 0,0,1,1
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: ForensicPad
        amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: forensic

- type: entity
  parent: BoxCardboard
  id: BoxDetonator
  name: detonator box
  description: A box of explosive detonators and triggers.
  components:
  - type: Item
    shape:
    - 0,0,1,1
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: EmptyDetonator
          amount: 3
        - id: TimerTrigger
          amount: 2
        - id: VoiceTrigger
  - type: Sprite
    layers:
    - state: box_security
    - state: trigger
