# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: CrateSecgear
  id: CrateSecurityArmor
  name: caisse d'armures
  description: Contient trois gilets pare-balles. Nécessite l'accès à la sécurité pour l'ouvrir.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: ClothingOuterArmorBulletproof
        amount: 3

- type: entity
  parent: CrateSecgear
  id: CrateSecurityHelmet
  name: caisse de casques
  description: Contient trois casques réglementaires. Nécessite l'accès à la sécurité pour l'ouvrir.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: ClothingHeadHelmetBasic
        amount: 3

- type: entity
  parent: CrateSecgear
  id: CrateSecurityNonlethal
  name: caisse de non-létaux
  description: Contient un assortiment de désactivateurs, matraques paralysantes et flashs. Nécessite l'accès à la sécurité pour l'ouvrir.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponDisabler
          amount: 3
        - id: Stunbaton
          amount: 3
        - id: BoxFlashbang
        - id: Flash
          amount: 3
#        - Pepperspray
#        - GrenadeTeargas

- type: entity
  parent: CrateSecgear
  id: CrateSecuritySupplies
  name: caisse de fournitures de sécurité
  description: Contient diverses fournitures pour l'équipe de Sécurité de la station. Nécessite l'accès à la sécurité pour l'ouvrir.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxHandcuff
        - id: BoxSechud
#        - SecBelt
#        - SecGasmask
#        - SpacelawBook

- type: entity
  parent: CrateSecgear
  id: CrateRestraints
  name: caisse de contentions
  description: Contient deux boîtes de menottes et deux boîtes de serflex. Nécessite l'accès à la sécurité pour l'ouvrir.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxHandcuff
          amount: 2
        - id: BoxZiptie
          amount: 2

- type: entity
  parent: CrateSecgear
  id: CrateSecurityBiosuit
  name: caisse de combinaisons biologiques de sécurité
  description: Contient 2 combinaisons biologiques pour qu'aucune maladie ne vous détourne de vos fonctions. Nécessite l'accès à la sécurité pour l'ouvrir.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillBiohazardGearSecurity
          rolls: 2
        - id: ClothingMaskSterile
          amount: 2

- type: entity
  parent: CrateSecgear
  id: CrateSecurityTrackingMindshieldImplants
  name: caisse d'implanteurs
  description: Contient 4 implants MindShield et 4 implants de localisation. Nécessite l'accès à la sécurité pour l'ouvrir.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: MindShieldImplanter
          amount: 4
        - id: TrackingImplanter
          amount: 4

- type: entity
  parent: CrateSecgear
  id: CrateSecNonlethalThrowables
  name: caisse de projectiles non-létaux
  description: "Contient une boîte de chaque : grenades aveuglantes, stingers, grenades lacrymogènes, et quatre bolas. Nécessite l'accès à la sécurité pour l'ouvrir."
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxFlashbang
        - id: BoxStinger
        - id: BoxTearGas
        - id: Bola # replace with 4 e-bolas when added
          amount: 4
