# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: CratePlastic
  id: CrateServiceJanitorialSupplies
  name: caisse de fournitures d'entretien
  description: Luttez contre la saleté avec les Essentiels de Nettoyage(mc) de Nanotrasen ! Contient trois seaux, panneaux de mise en garde et grenades nettoyantes. Comprend aussi une serpillière, un balai, un nettoyant en spray, une brosse métallique, un chiffon et un sac poubelle.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: AllSoapsTable
        - id: MopItem
        - id: MopBucketCubeWrapped
        - id: Bucket
          amount: 3
        - id: WetFloorSign
          amount: 2
        - id: SprayBottleSpaceCleaner
          amount: 2
        - id: TrashBag
          amount: 2
        - id: Plunger
          amount: 2
        - id: BoxCleanerGrenades
        - id: WireBrush
          amount: 2

- type: entity
  parent: CratePlastic
  id: CrateServiceCleanerGrenades
  name: caisse de grenades nettoyantes en gros
  description: Contient deux boîtes de grenades nettoyantes, pour les taches les plus tenaces.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxCleanerGrenades
        amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceReplacementLights
  name: caisse de lumières de rechange
  description: Que la lumière d'Aether brille sur cette station ! Ou du moins, la lumière de quarante-deux tubes fluorescents et vingt et un ampoules.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLighttube
        - id: BoxLightbulb

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceColorfulLights
  name: colorful lights crate
  description: It's not a party until it's hard to see, a little disorienting, and your ears hurt. Contains twelve light tubes and twelve light bulbs in a variety of colors.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLightbulbColorfulMixed
        - id: BoxLighttubeColorfulMixed

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceHolidayLights
  name: caisse de guirlandes de fêtes
  description: Décorez les couloirs avec ces guirlandes festives !
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxLighttubeHoliday
        amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateMousetrapBoxes
  name: caisse de pièges à souris
  description: Des pièges à souris, pour quand tout le service est hanté par une horde entière de rats. À utiliser avec modération... ou pas.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxMousetrap

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceSmokeables
  name: caisse de fumables
  description: Fatigué d'une mort rapide sur la station ? Commandez cette caisse et fumez en chaîne vers une mort toussotante !
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:GroupSelector
          children:
          - id: CigCartonGreen
            weight: 0.50
          - id: CigCartonRed
        - !type:GroupSelector
          children:
          - id: CigCartonBlue
            weight: 0.50
          - id: CigCartonBlack
        - !type:GroupSelector
          children:
          - id: CigarGoldCase
            weight: 0.05
          - id: CigarCase
        - id: Matchbox
          amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceTheatre
  name: caisse de performances théâtrales
  description: Contient une cape de mite, des ciseaux de coiffeur, un uniforme de femme de chambre, des accessoires de clown et de mime, et d'autres charmes de spectacle.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BarberScissors
        - id: ClothingOuterSuitMonkey
        - id: ClothingHeadHatAnimalMonkey
        - id: ClothingUniformJumpskirtJanimaid
        - id: ClothingUniformJumpskirtOldDress
        - id: ClothingHeadHatMagician
        - !type:AllSelector # Cloaks
          children:
          - id: ClothingNeckCloakMoth
          - id: ClothingNeckCloakVoid
        - !type:AllSelector # Clown starter kit
          children:
          - id: ClothingMaskClown
          - id: ClownRecorder
          - !type:GroupSelector
            children:
            - id: ClothingShoesClown
            - id: ClothingShoesClownLarge
              weight: 0.1
          - !type:NestedSelector
            tableId: RandomBikeHornTable
        - !type:AllSelector # Mime starter kit
          children:
          - id: ClothingMaskMime
          - id: ClothingBeltSuspendersRed
          - id: ClothingBeltSuspendersBlack
        - !type:AllSelector # Performer starter kit
          children:
          - id: ClothingUniformJumpskirtPerformer
          - id: ClothingShoesBootsPerformer
          - id: ClothingHeadPerformerWig

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceCustomSmokable
  name: caisse de fumables DIY
  description: Vous voulez être créatif dans la manière de détruire vos poumons ? Alors cette caisse est faite pour vous ! Tout le nécessaire pour rouler vos propres cigarettes.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: PackPaperRolling
        - id: CigaretteFilter
          amount: 8
        - id: GroundTobacco
          amount: 4
        - id: SmokingPipe
        - id: Matchbox

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceBureaucracy
  name: caisse de bureaucratie
  description: Plusieurs piles de papier, quelques stylos et un jouet de bureau. Que demander de plus ?
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: Paper
          amount: 12
        - id: PaperOffice
          amount: 6
        - id: Pen
          amount: 2
        - id: BoxFolderClipboardEmpty
          amount: 2
        - id: HandLabeler
        - id: BoxFolderBlueEmpty
        - id: BoxFolderRedEmpty
        - id: BoxFolderYellowEmpty
        - id: NewtonCradle
        - id: BoxEnvelope
        - id: BrbSign

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceFaxMachine
  name: caisse de télécopieur
  description: Un télécopieur et un tournevis pour configurer le nom.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: Screwdriver
        - id: FaxMachineFlatpack

- type: entity
  parent: CrateCommandSecure
  id: CrateServicePersonnel
  name: caisse de personnel
  description: Contient une boîte de cartes d'identité vierges et de PDA.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxPDA
        - id: BoxID

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceBooks
  name: caisse de livres
  description: Contient 10 livres vides d'apparence aléatoire.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BookRandom
        amount: 10

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceGuidebooks
  name: caisse de guides
  description: Contient des guides.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BookSpaceEncyclopedia
        - id: BookTheBookOfControl
        - id: BookBartendersManual
        - id: BookHowToCookForFortySpaceman
        - id: BookLeafLoversSecret
        - id: BookEngineersHandbook
        - id: BookScientistsGuidebook
        - id: BookSecurity
        - id: BookHowToKeepStationClean
        - id: BookHowToRockAndStone
        - id: BookMedicalReferenceBook
        - id: BookHowToSurvive
        - id: BookChemicalCompendium
        - id: BookSpaceLaw

- type: entity
  parent: CrateFreezer
  id: CrateServiceSodaDispenser
  name: caisse de recharges pour distributeur de sodas
  description: Contient des recharges pour distributeurs de sodas.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: DrinkCoffeeJug
        - id: DrinkColaBottleFull
        - id: DrinkCreamCartonXL
        - id: DrinkDrGibbJug
        - id: DrinkEnergyDrinkJug
        - id: DrinkGreenTeaJug
        - id: DrinkIceJug
        - id: DrinkJuiceLimeCartonXL
        - id: DrinkJuiceOrangeCartonXL
        - id: DrinkLemonLimeJug
        - id: DrinkRootBeerJug
        - id: DrinkSodaWaterBottleFull
        - id: DrinkSpaceMountainWindBottleFull
        - id: DrinkSpaceUpBottleFull
        - id: DrinkSugarJug
        - id: DrinkTeaJug
        - id: DrinkTonicWaterBottleFull
        - id: DrinkWaterMelonJuiceJug

- type: entity
  parent: CrateFreezer
  id: CrateServiceBoozeDispenser
  name: caisse de recharges pour distributeur d'alcool
  description: Contient des recharges pour distributeurs d'alcool.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: DrinkAleBottleFullGrowler
        - id: DrinkBeerGrowler
        - id: DrinkCoffeeLiqueurBottleFull
        - id: DrinkCognacBottleFull
        - id: DrinkGinBottleFull
        - id: DrinkMeadJug
        - id: DrinkRumBottleFull
        - id: DrinkTequilaBottleFull
        - id: DrinkVermouthBottleFull
        - id: DrinkVodkaBottleFull
        - id: DrinkWhiskeyBottleFull
        - id: DrinkWineBottleFull

- type: entity
  parent: CratePlastic
  id: CrateServiceBox
  name: caisse de boîtes
  description: Contient 6 boîtes polyvalentes vides.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxCardboard
        amount: 6

- type: entity
  parent: CratePlastic
  id: CrateJanitorBiosuit
  name: caisse de combinaisons biologiques de concierge
  description: Contient 2 combinaisons biologiques pour qu'aucune maladie ne vous détourne du nettoyage.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillBiohazardGearJanitor
          rolls: 2
        - id: ClothingMaskSterile
          amount: 2

- type: entity
  parent: CrateTrashCart
  id: CrateTrashCartFilled
  suffix: Rempli
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
          # Creatures
        - id: MobCockroach
          prob: 0.05
        - id: MobMothroach
          prob: 0.03
        - id: MobMouse
          prob: 0.05
        - id: MobLootbug # Goobstation
          prob: 0.02
          # Food Packaging
        - id: FoodPacketBoritosTrash
          prob: 0.1
        - id: FoodPacketCheesieTrash
          prob: 0.1
        - id: FoodPacketChipsTrash
          prob: 0.1
        - id: FoodPacketSusTrash
          prob: 0.1
        - id: FoodPacketSyndiTrash
          prob: 0.1
        - id: FoodPacketChowMeinTrash
          prob: 0.1
        - id: FoodPacketDanDanTrash
          prob: 0.1
        - id: FoodPacketMRETrash
          prob: 0.1
        - id: FoodPacketPistachioTrash
          prob: 0.1
        - id: FoodPacketSemkiTrash
          prob: 0.1
        - id: FoodPacketRaisinsTrash
          prob: 0.1
          # Cans
        - id: FoodTinBeansTrash
          prob: 0.15
        - id: FoodTinPeachesTrash
          prob: 0.15
        - id: FoodTinMRETrash
          prob: 0.15
          # Cigarette Stuff
        - id: Ash
          prob: 0.15
          # Bacteria
        - id: FoodBreadMoldySlice
          prob: 0.15
        - id: FoodPizzaMoldySlice
          prob: 0.15
          # Botanical Waste
        - id: TrashBananaPeel
          prob: 0.15
        - id: FoodCornTrash
          prob: 0.15
          # Misc
        - id: DrinkGlass
          prob: 0.15
        - id: BrokenBottle
          prob: 0.15
        - id: LightTubeBroken
          prob: 0.15
        - id: LightBulbBroken
          prob: 0.15
        - id: MobMouseDead
          prob: 0.1
        - id: Syringe
          prob: 0.1
        - id: ShardGlassPlasma
          prob: 0.1

- type: entity
  parent: CrateGenericSteel
  id: CrateCandles
  name: caisse de bougies
  description: Contient 4 boîtes de bougies, 2 grandes et 2 petites. Pour l'ambiance ou autre chose.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxCandle
          amount: 2
        - id: BoxCandleSmall
          amount: 2
